version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  app:
    build: .
    container_name: login-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_URL=mongodb://localhost:27017/
      - MONGODB_DATABASE=login-service
      - APP_NAME=login-service
      - JWT_KEY=5768e54bb7cba2d807f13cd3901c62ac2c240f3f
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://host.docker.internal:4566
      - USER_POOL_ID=us-east-1_94182b9942bc4895b5c05af22da60002
      - CLIENT_ID=4vgqpvzn0u1x8u8cxfncnvje59

volumes:
  mongo-data:
