// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	config "github.com/Gaurav-malwe/login-service/config"
	cognitoidentityprovider "github.com/aws/aws-sdk-go/service/cognitoidentityprovider"

	mock "github.com/stretchr/testify/mock"
)

// CognitoClient is an autogenerated mock type for the CognitoClient type
type CognitoClient struct {
	mock.Mock
}

// NewCognitoClient provides a mock function with given fields: _a0
func (_m *CognitoClient) NewCognitoClient(_a0 *config.Config) (*cognitoidentityprovider.CognitoIdentityProvider, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NewCognitoClient")
	}

	var r0 *cognitoidentityprovider.CognitoIdentityProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(*config.Config) (*cognitoidentityprovider.CognitoIdentityProvider, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*config.Config) *cognitoidentityprovider.CognitoIdentityProvider); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cognitoidentityprovider.CognitoIdentityProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(*config.Config) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCognitoClient creates a new instance of CognitoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCognitoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CognitoClient {
	mock := &CognitoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
