// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Confirm provides a mock function with given fields: ginCtx
func (_m *Controller) Confirm(ginCtx *gin.Context) {
	_m.Called(ginCtx)
}

// Login provides a mock function with given fields: ginCtx
func (_m *Controller) Login(ginCtx *gin.Context) {
	_m.Called(ginCtx)
}

// Register provides a mock function with given fields: ginCtx
func (_m *Controller) Register(ginCtx *gin.Context) {
	_m.Called(ginCtx)
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
